# Generated by Django 4.0.4 on 2022-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last', models.CharField(max_length=250)),
                ('avg', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
    ]
