# Generated by Django 4.0.4 on 2022-05-04 16:39

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_dbm_ida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbm',
            name='ida',
            field=models.CharField(default=builtins.id, max_length=250),
        ),
    ]
