# Generated by Django 4.0.4 on 2022-05-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_alter_dbm_ida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbm',
            name='ida',
        ),
    ]
