# Generated by Django 4.0.4 on 2022-05-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_remove_dbm_ida'),
    ]

    operations = [
        migrations.CreateModel(
            name='nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=40)),
            ],
        ),
    ]
