# Generated by Django 4.0.4 on 2022-05-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=20)),
                ('StoreAbout', models.TextField(max_length=50)),
                ('StoreAvg', models.IntegerField()),
            ],
        ),
    ]
