# Generated by Django 4.0.4 on 2022-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0006_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NavName', models.CharField(max_length=20)),
            ],
        ),
    ]
