# Generated by Django 4.0.4 on 2022-05-08 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0007_storenav'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='hrf',
            field=models.CharField(default=datetime.datetime(2022, 5, 8, 18, 9, 40, 272371, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
