# Generated by Django 4.0.4 on 2022-05-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0008_nav_hrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='hrf',
            field=models.CharField(max_length=40),
        ),
    ]
