# Generated by Django 4.0.4 on 2022-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0009_alter_nav_hrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTitle', models.CharField(max_length=10)),
                ('CAbout', models.TextField()),
                ('CPrice', models.IntegerField()),
                ('Cimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
