# Generated by Django 4.0.4 on 2022-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='CAbout',
            field=models.TextField(max_length=100),
        ),
    ]
