# Generated by Django 4.0.4 on 2022-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0011_alter_cart_cabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cartitle', models.CharField(max_length=30)),
                ('CarAbout', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='CAbout',
            field=models.TextField(default='Enter Youer Text', max_length=100),
        ),
    ]
