# Generated by Django 4.0.4 on 2022-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0012_sendfree_alter_cart_cabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendfree',
            name='CarAbout',
            field=models.TextField(max_length=70),
        ),
    ]
