# Generated by Django 4.0.4 on 2022-05-12 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0013_alter_sendfree_carabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfree',
            name='logo',
            field=models.CharField(default=datetime.datetime(2022, 5, 12, 17, 30, 23, 400960, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
