# Generated by Django 4.0.4 on 2022-05-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0014_sendfree_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendfree',
            old_name='logo',
            new_name='Carlogo',
        ),
    ]
