# Generated by Django 4.0.4 on 2022-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0015_rename_logo_sendfree_carlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdTitle', models.CharField(max_length=250)),
                ('ProdAbout', models.CharField(max_length=250)),
                ('ProdPrice', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='dbm',
        ),
    ]
