# Generated by Django 4.0.4 on 2022-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0017_productslider_prodimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SliderImgs', models.ImageField(upload_to='sliders/')),
            ],
        ),
    ]
