# Generated by Django 4.0.4 on 2022-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0018_slidertitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cimg',
            field=models.ImageField(upload_to='SliderCart/'),
        ),
    ]
