# Generated by Django 4.0.4 on 2022-05-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0019_alter_cart_cimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(upload_to='Logo/')),
            ],
        ),
    ]
