# Generated by Django 4.0.4 on 2022-05-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0022_towimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContImg', models.ImageField(upload_to='bg-contact')),
            ],
        ),
    ]
