# Generated by Django 4.0.4 on 2022-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0024_alter_cart_ctitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='ContactAbout',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='ContactLogo',
            field=models.ImageField(blank=True, null=True, upload_to='Logo/'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='ContactTitle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
