# Generated by Django 4.0.4 on 2022-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0025_contacts_contactabout_contacts_contactlogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='ContImg',
            field=models.ImageField(upload_to='bg-contact/'),
        ),
    ]
