# Generated by Django 4.0.4 on 2022-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0026_alter_contacts_contimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='times',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
