# Generated by Django 4.0.4 on 2022-05-14 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0027_contacts_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='times',
        ),
        migrations.AddField(
            model_name='productslider',
            name='times',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
