# Generated by Django 4.0.4 on 2022-05-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0028_remove_contacts_times_productslider_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenav',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='productslider',
            name='ProdAbout',
            field=models.CharField(max_length=38),
        ),
    ]
