# Generated by Django 4.0.4 on 2022-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0029_storenav_logo_alter_productslider_prodabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='storenav',
            name='hrf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
