# Generated by Django 4.0.4 on 2022-05-20 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0030_storenav_hrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='forimgbottom',
            name='dates',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
