# Generated by Django 4.0.4 on 2022-05-20 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0031_forimgbottom_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertitle',
            name='Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
