# Generated by Django 4.0.4 on 2022-05-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0032_slidertitle_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True, verbose_name='نماییش داده شود یا نه')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('pos', models.IntegerField(verbose_name='پوزشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['pos'],
            },
        ),
        migrations.AlterModelOptions(
            name='changelogo',
            options={'verbose_name': 'تغیر لوگو در تمام صفحات'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'تغیر مشخصات صفحه در باره ما یا تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='forimgbottom',
            options={'verbose_name': 'تغیر یا اضافه کردن عکس به قسمت چهار عکس'},
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'verbose_name': 'تغیر عنوان صفحه اصلی'},
        ),
        migrations.AlterModelOptions(
            name='productslider',
            options={'verbose_name': 'تغیر و اضافه کردن محصول '},
        ),
        migrations.AlterModelOptions(
            name='sendfree',
            options={'verbose_name': 'تغیر خدمات ارسال'},
        ),
        migrations.AlterModelOptions(
            name='slidertitle',
            options={'verbose_name': 'اضافه کردن عکس به سلایدر اول صفحه'},
        ),
        migrations.AlterModelOptions(
            name='storenav',
            options={'verbose_name': 'تغیر عنوان صفحه فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='towimg',
            options={'verbose_name': 'تغیر دو عکس پایین صفحه'},
        ),
    ]
