# Generated by Django 4.0.4 on 2022-05-27 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0034_productslider_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productslider',
            old_name='category',
            new_name='categorys',
        ),
        migrations.AlterField(
            model_name='productslider',
            name='ProdAbout',
            field=models.CharField(max_length=38, verbose_name='در باره محصول مختصر'),
        ),
        migrations.AlterField(
            model_name='productslider',
            name='ProdImg',
            field=models.ImageField(blank=True, null=True, upload_to='%y/%m/%d', verbose_name='تغیر یا اضافه کردن عکس محصول'),
        ),
        migrations.AlterField(
            model_name='productslider',
            name='ProdPrice',
            field=models.IntegerField(verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='productslider',
            name='ProdTitle',
            field=models.CharField(max_length=250, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productslider',
            name='about',
            field=models.TextField(verbose_name='در باره محصول کلی'),
        ),
        migrations.AlterField(
            model_name='productslider',
            name='times',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ انتشار محصول'),
        ),
    ]
